spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080
#  host:
#    api: http://localhost:8080
#    front: https://banking-api.sample.com
